### ISSUE TITLE
tb-mac-v3-signing* `clientId` and `accessToken` are missing

### ISSUE THREAD

**Issue by escapewindow** [mozilla-platform-ops/ronin_puppet#174]
I'm not sure if this is a config issue or a secrets issue or both.

`tb-mac-v3-signing2` had a missing `clientId` and `accessToken`. When I copied them over from `tb-mac-v3-signing1`, it started working. I then rebooted because I had two worker daemons running and I had issues trying to kill one. Puppet ran, and wiped the `clientId` and `accessToken`. I killed puppet, manually entered them, and it seems to be running.

Looks like we need to fix something to populate this properly?

CC @davehouse @srfraser

**Comment by srfraser** [comment]
Puppet shouldn't be running at boot any more, assuming it got the changes with https://github.com/mozilla-platform-ops/ronin_puppet/pull/164 

I don't have access to the vault to verify the secrets required

**Comment by davehouse** [comment]
The puppet atboot plist is still in place. I missed that in #164; I'll remove it across the scriptworkers. https://bugzilla.mozilla.org/show_bug.cgi?id=1609467
