### ISSUE TITLE
run puppet on mac signers periodically

### ISSUE THREAD

**Issue by escapewindow** [mozilla-platform-ops/ronin_puppet#267]
https://jira.mozilla.com/browse/RELENG-230

@dividehex @davehouse we're planning on running puppet on the mac signers periodically, so we can land dependency bumps and config changes and have them take effect without having to ssh in. This should reduce the security concern of sshing in and the maintenance concern of human error.

Thoughts on this? Should we just add a wrapper script that pulls the latest ronin_puppet and runs puppet, or is there a better way of doing this?

**Comment by dividehex** [comment]
<commented in Jira ticket>
