### ISSUE TITLE
puppet broken on mac signers?

### ISSUE THREAD

**Issue by escapewindow** [mozilla-platform-ops/ronin_puppet#332]
> Error: Evaluation Error: Error while evaluating a Function Call, [hiera-vault] no token set in options and no token in VAULT_TOKEN (file: /etc/puppet/environments/production/code/modules/roles_profiles/manifests/profiles/logging.pp, line: 56, column: 41) on node mac-v3-signing9.srv.releng.mdc1.mozilla.com
curl: (22) The requested URL returned error: 401

1) How do we fix this? Do we have to reimage the entire pool?

2) I wish we could somehow keep track of things like this. Per [this comment](https://github.com/mozilla-platform-ops/ronin_puppet/pull/328#issuecomment-878504517), I manually puppetized one mac signer to see if things would work, but I could see us someday rolling out a change to `production-mac-signing` that bricks the entire mac signing pool.

**Comment by escapewindow** [comment]
@dividehex

**Comment by dividehex** [comment]
> 
> 
> > Error: Evaluation Error: Error while evaluating a Function Call, [hiera-vault] no token set in options and no token in VAULT_TOKEN (file: /etc/puppet/environments/production/code/modules/roles_profiles/manifests/profiles/logging.pp, line: 56, column: 41) on node mac-v3-signing9.srv.releng.mdc1.mozilla.com
> > curl: (22) The requested URL returned error: 401
> 
>     1. How do we fix this? Do we have to reimage the entire pool?

No need to reimage.  It should be fixed with PR 330.  The puppet script should pull the fix and run puppet again.

>     2. I wish we could somehow keep track of things like this. Per [this comment](https://github.com/mozilla-platform-ops/ronin_puppet/pull/328#issuecomment-878504517), I manually puppetized one mac signer to see if things would work, but I could see us someday rolling out a change to `production-mac-signing` that bricks the entire mac signing pool.

Maybe we should talk about this over zoom.  "Bricking" is always a risk and there are ways to mitigate it but we will need to collaborate and plan something out.

**Comment by dividehex** [comment]
#330

**Comment by escapewindow** [comment]
I applied the run-puppet.sh changes on mac-v3-signing9, and now I'm getting

```
Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Fluentd]: parameter 'syslog_port' expects an Integer value, got String (file: /etc/puppet/environments/production/code/modules/roles_profiles/manifests/profiles/logging.pp, line: 50, column: 13) on node mac-v3-signing9.srv.releng.mdc1.mozilla.com
```

**Comment by escapewindow** [comment]
Looks like #333 and #330 fixed this, thank you! I'm not sure how best to catch changes that might brick the pool automatically, without spending a ton of time on the solution. Maybe if we're somehow able to detect if changes in ronin-puppet affect the mac pool? Though vault changes could also affect it.

**Comment by escapewindow** [comment]
Current status: Getting

> + email_report 'Puppet apply failed on mac-v3-signing9.srv.releng.mdc1.mozilla.com' 'Error: Evaluation Error: Error while evaluating a Function Call, '\''new'\'' The string '\'''\'' cannot be converted to Integer (file: /etc/puppet/environments/production/code/modules/roles_profiles/manifests/profiles/logging.pp, line: 57, column: 41) on node mac-v3-signing9.srv.releng.mdc1.mozilla.com'
> + ERR_SUBJECT='Puppet apply failed on mac-v3-signing9.srv.releng.mdc1.mozilla.com'
> + ERR_MSG='Error: Evaluation Error: Error while evaluating a Function Call, '\''new'\'' The string '\'''\'' cannot be converted to Integer (file: /etc/puppet/environments/production/code/modules/roles_profiles/manifests/profiles/logging.pp, line: 57, column: 41) on node mac-v3-signing9.srv.releng.mdc1.mozilla.com'

I'm planning on cherry-picking #335 to production-mac-signing and fork, until we can fix `master` on the mac signers.

**Comment by escapewindow** [comment]
Also

> HEAD is now at 8ab2105d Merge pull request #333 from dividehex/fix_papertrail_lookup
Error: Evaluation Error: Error while evaluating a Function Call, 'new' The string '' cannot be converted to Integer (file: /etc/puppet/environments/production/code/modules/roles_profiles/manifests/profiles/logging.pp, line: 57, column: 41) on node mac-v3-signing9.srv.releng.mdc1.mozilla.com
> curl: (22) The requested URL returned error: 401

**Comment by escapewindow** [comment]
I think this is resolved, thank you!
