### ISSUE TITLE
circle ci tasks are broken

### ISSUE THREAD

**Issue by escapewindow** [mozilla-platform-ops/ronin_puppet#378]
`failed to create host: Image xcode:11.1.0 is not supported` for the macos integration tests, and

```
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [{
  "message": "Couldn't login to Azure, please verify your tenant id, client id and client secret",
  "request": null,
  "response": null
}
```

for the windows integration tests.

**Comment by markcor** [comment]
@davehouse @aerickson

**Comment by davehouse** [comment]
The version of xcode we were on is removed from circleci now. There are newer 11.x xcode so I picked the latest and verified our tests are okay: https://github.com/mozilla-platform-ops/ronin_puppet/pull/379

@markcor are the azure secrets in circleci good, or is that failure something else? (can you check https://app.circleci.com/settings/organization/github/mozilla-platform-ops/contexts/b699bdb3-38ef-4188-9f9a-9c877edc7ba6 )

**Comment by aerickson** [comment]
I believe this was fixed. Closing.
