### ISSUE TITLE
windows integration tests are broken

### ISSUE THREAD

**Issue by aerickson** [mozilla-platform-ops/ronin_puppet#381]
`  "message": "Couldn't login to Azure, please verify your tenant id, client id and client secret",`

example of failure:
https://app.circleci.com/pipelines/github/mozilla-platform-ops/ronin_puppet/703/workflows/214aceef-ac1c-4316-b316-660f342d39fb/jobs/3141

Mark, should we disable the test or would you like get them working again?

**Comment by jwmoss** [comment]
Using expired client secret. @markcor will update.

**Comment by jwmoss** [comment]
Updated the expiring secret, [which seems to fix the tests](https://app.circleci.com/pipelines/github/mozilla-platform-ops/ronin_puppet/786/workflows/1516154d-4a7a-43f3-a24b-3167988a5844/jobs/3608).

**Comment by aerickson** [comment]
The secret fix has worked. Thank you both!
